name: Main Workflow

on:
  push:
    branches:
      - main

jobs:

  call-docker-workflow:

    uses: manojkolagana25/github-reusable-workflow-demo/.github/workflows/docker-build.yml@main

    with:
      image_name: demo-python-app
