name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-push:

    uses: manojkolagana25/github-reusable-workflow-demo/.github/workflows/docker-build.yml@main

    with:
      image_name: manojkolagana25/demo-python-app:latest
